api/package-lock.json, client/src/components/ejemplo.jsx
=> otra prueba

api/app.js, api/db.js, api/models/Events.js, api/models/Productor.js, api/models/Ticked.js, api/models/Usuario.js, api/package-lock.json, api/package.json
=> tratando de hacer la base de datos

README.md, client/src/components/ejemplo.jsx
=> Prueba Actual

client/src/components/CardBigEvent/CardBigEvent.jsx, client/src/components/CardEvent/CardEvent.jsx, client/src/components/Detail/Detail.jsx, client/src/components/Filters/Date/Date.jsx, client/src/components/Filters/Genre/Genre.jsx, client/src/components/Footer/Footer.jsx, client/src/components/Home/Home.jsx, client/src/components/NavBar/NavBar.jsx, client/src/components/SearchBar/SearchBar.jsx, client/src/components/ejemplo.jsx
=> Front update

api/controllers/Usuario.js, api/routes/index.js
=> Feature agus2

client/src/components/CardEvent/CardEvent.jsx, client/src/components/SearchBar/SearchBar.jsx, client/src/redux/reducer.js
CardEvent component, SearchBar component
=> CardEvent y Search

api/controllers/Events.js, api/models/Events.js, api/models/Usuario.js, api/package-lock.json, api/package.json, api/routes/index.js
[Modificacion: Ruta GET events y Cargado de datos de Eventos a DB. Br
=> Modificacion: Ruta GET events y Cargado de datos de Eventos a DB. Br

api/controllers/Events.js, api/routes/index.js
eventos GET POST PUT Y GET:NAME.
=> eventos GET POST PUT Y GET:NAME.

api/controllers/Events.js, api/routes/index.js
"correcion: Events variable Events a event"
=> "correcion: Events variable Events a event"

api/controllers/Genres.js, api/db.js, api/routes/index.js
=> Feature agus

api/db_event_genre/db_events.json
sumo una foto que faltaba agregar
=> Feature diego

api/db_event_genre/db_events.json
=> changes db isBig Diego

client/src/components/Filters/Genre/Genre.jsx, client/src/redux/actions.js, client/src/redux/reducer.js
=> FILTRO GENERO

client/src/components/Detail/Detail.jsx
=> clear detail

client/src/components/Filters/Date/Date.jsx, client/src/components/Filters/Genre/Genre.jsx, client/src/components/NavBar/NavBar.jsx, client/src/redux/actions.js, client/src/redux/reducer.js
=> Filtros Reparados

client/src/components/Calendar/Calendar.jsx, client/src/components/Filters/Date/Date.jsx, client/src/components/Filters/Genre/Genre.jsx, client/src/components/Home/Home.jsx, client/src/components/NavBar/NavBar.jsx, client/src/components/Paginado/PaginadoBigEvents.jsx, client/src/components/Paginado/PaginadoEvents.jsx
=> Paginado reparado

client/src/components/CardBigEvent/CardBigEvent.module.css, client/src/components/Home/Home.jsx, client/src/components/Home/Home.module.css, client/src/components/Paginado/PaginadoBigEvents.jsx, client/src/components/Paginado/PaginadoBigEvents.module.css, client/src/components/Paginado/PaginadoEvents.jsx, client/src/components/Paginado/PaginadoEvents.module.css
=> Css Pagination

client/src/components/Footer/Footer.jsx
agrego prop target en link de redes sociales
=> Feature noe

client/src/components/Contact/Contact.jsx, client/src/components/Contact/Contact.module.css, client/src/components/Modals/Modal/Modal.module.css, client/src/index.css
Modificaciones: Modal Contact CSS
=> Modificaciones: Modal Contact CSS

client/src/components/Home/Home.module.css, client/src/components/RegisterEvent/RegisterEvents.jsx, client/src/components/RegisterEvent/RegisterEvents.module.css
diseño temporal registro evento
=> diseño temporal registro evento

client/src/components/Calendar/Calendar.jsx, client/src/components/Detail/Detail.jsx, client/src/components/ModalCalendar/ModalCalendar.jsx, client/src/components/RegisterEvent/RegisterEvents.jsx
=> cambios en general

client/src/components/Contact/Contact.jsx, client/src/components/Contact/Contact.module.css, client/src/components/Detail/Detail.jsx, client/src/components/RegisterEvent/RegisterEvents.jsx
=> corrección de formularios

client/src/components/Calendar/Calendar.module.css, client/src/components/Carousel/Carousel.module.css, client/src/components/Home/Home.module.css
=> Modificacion: Scroll

client/package-lock.json, client/package.json, client/src/components/Carousel/Carousel.jsx, client/src/components/Detail/Detail.jsx, client/src/components/Detail/Detail.module.css, client/src/components/Map/Map.jsx
=> Map and detail

api/controllers/Venue.js, api/models/Venue.js, api/routes/index.js
venue changes, and Post route for venues
=> venue changes, and Post route for venues

api/app.js, api/controllers/Login.js, api/controllers/Producer.js, api/controllers/User.js, api/controllers/Venue.js, api/db.js, api/middlewares/auth.js, api/models/Producer.js, api/models/TicketStock.js, api/models/User.js, api/package-lock.json, api/package.json, api/routes/index.js
Creacion: Validaciones en las rutas y JWT creado Autenticaciones y middlewares isAdmin, isProducer
=> Creacion: Validaciones en las rutas y JWT creado Autenticaciones y middlewares isAdmin, isProducer

api/controllers/User.js, api/middlewares/auth.js, api/routes/index.js, client/package-lock.json, client/src/App.js, client/src/components/Admin/adminPanel.jsx, client/src/redux/actions.js, client/src/redux/reducer.js
Product backlog Administrador Work
=> Product backlog Administrador Work

client/src/App.js, client/src/components/LoginAuth0/LoginAuth0.jsx, client/src/components/LogoutAuth0/PerfilYLogoutAuth0.jsx, client/src/redux/reducer.js
actualizaciones en login y logout
=> actualizaciones en login y logout

client/src/components/LoginAuth0/LoginAuth0.jsx, client/src/components/ProfileUser/NavBarProfile/NavBarProfile.jsx
=> actualizaciones de perfil

api/controllers/BlackList.js, api/controllers/User.js, api/models/BlackList.js, api/routes/index.js
Modificacion: Usuarios baneados desde panel de admin y Backend
=> Modificacion: Usuarios baneados desde panel de admin y Backend

client/src/components/Admin/AdminEventPanel.jsx, client/src/components/Admin/AdminUserPanel.jsx, client/src/redux/actions.js, client/src/redux/reducer.js
=> SearchBar Event Creation

client/src/components/Cart/Cart.jsx, client/src/components/Cart/Cart.module.css, client/src/components/Detail/Detail.jsx, client/src/components/Detail/Detail.module.css, client/src/components/Modals/Modal/Modal2.module.css, client/src/components/NavBar/NavBar.jsx, client/src/components/NavBar/NavBar.module.css
=> Cart and detail fixes

client/src/components/TicketVoucher/TicketVoucher.jsx, client/src/components/TicketVoucher/TicketVoucher.module.css
=> Voucher ticket Front

client/src/components/Admin/AdminOrdersPanel.jsx, client/src/components/Admin/AdminOrdersPanel.module.css, client/src/components/Admin/AdminUserPanel.jsx, client/src/components/Admin/AdminUserPermised.module.css, client/src/components/Admin/CardOrder.jsx, client/src/components/Admin/DetailOrdersAdmin.jsx, client/src/components/Admin/DetailOrdersAdmin.module.css, client/src/components/Admin/PerfilEventAdmin.module.css, client/src/components/Admin/adminPanel.jsx, client/src/redux/actions.js, client/src/redux/reducer.js
"Creacion: Panel admin Ordenes de compra"
=> "Creacion: Panel admin Ordenes de compra"

api/controllers/Tickets.js, api/models/Ticket.js
=> Feature adminpanel

client/src/components/Detail/NavBarDetail/NavBarDetail.jsx, client/src/components/ProfileUser/NavBarProfile/NavBarProfile.jsx, client/src/components/ProfileUser/NavBarProfile/NavBarProfile.module.css, client/src/components/ProfileUser/Profile.module.css
=> Feature solana

client/src/components/Modals/Modal/Modal.module.css
=> Repairs on Contact Modal

client/src/components/Footer/Footer.module.css
=> Footer fonts

api/controllers/BlackList.js, api/controllers/Events.js, api/controllers/Genres.js, api/controllers/Likes.js, api/controllers/ShoppingCart.js, api/controllers/TicketStock.js, api/controllers/Tickets.js, api/controllers/User.js, api/controllers/Validations.js, api/controllers/Venue.js, api/middlewares/auth.js, api/routes/index.js
Modifaciones: Catch en varias rutas y Status Correcto
=>  Modifaciones: Catch en varias rutas y Status Correcto

client/src/components/Detail/NavBarDetail/NavBarDetail.jsx, client/src/components/Detail/NavBarDetail/navBarD.module.css, client/src/components/NavBar/NavBar.jsx
=> Cart in new NavBar

client/public/index.html
=> Feature noe prueba

client/src/App.js, client/src/components/Carousel2/Carousel2.jsx, client/src/components/Home/Home.jsx, client/src/components/ModalCalendar/ModalCalendar.jsx
=> From /:id to /detail/:id

client/src/components/Filters/Genre/Genre.jsx
=> toUpperCase in filter genres

api/controllers/TicketVoucher.js, client/src/App.js
Repairs Vocucher and Endpoints
=> Repairs Vocucher and Endpoints
